---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ecsteam/spring-boot
    tag: '1.5.1.RELEASE'

inputs:
- name: master
  path: src
- name: version-output

outputs:
- name: build-output

run:
  path: src/ci/tasks/build-jar.sh
